FROM python:3.11

# Copy using poetry.lock* in case it doesn't exist yet
COPY ./frontend /frontend

WORKDIR frontend

RUN pip install -r requirements.txt

# CMD ["tail", "-f", "/dev/null"]
CMD ["streamlit", "run", "gui.py", "--theme.base=dark"]
